language: node_js
node_js:
  - '0.10'
  - '0.12'

install:
  - time npm install
  - time npm install istanbul coveralls

script:
  - ./node_modules/.bin/istanbul cover --config="scripts/istanbul.yml" ./node_modules/.bin/minijasminenode2 ./test.js

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
